---
- name: Deploy App
  hosts: "{{ env }}:host1"
  become: true

  vars_files:
    - "vars/{{ env }}.yml"

  tasks:
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Create the application/nginx directories
      file:
        path: "{{ item }}" 
        state: directory
        mode: '0755'
      loop:
      - /opt/app
      - /etc/nginx

    - name: Render and Copy {{ env }} environment application configuration
      template:
        src: templates/.nginx.conf.j2
        dest: /opt/app/nginx.conf
      vars:
        config: "{{ spec }}"

    - name: Render and Copy {{ env }} environment nginx configuration
      template:
        src: templates/.env.j2
        dest: /opt/app/.env
      vars:
        config: "{{ spec }}"

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /opt/app/docker-compose.yml
        mode: 0644

    - name: Create Docker volumes
      docker_volume:
        name: secret-keys-volume

    - name: Deploy Docker Compose
      docker_compose:
        project_src: /opt/app
        state: present
        restarted: true

    - name: Ensure app instances are reachable
      wait_for:
        port: 8181
